create table if not exists public.user_question_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  note text not null default '',
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (user_id, question_id)
);

create index if not exists user_question_notes_user_id_idx
  on public.user_question_notes (user_id);

create index if not exists user_question_notes_question_id_idx
  on public.user_question_notes (question_id);

alter table public.user_question_notes enable row level security;

drop policy if exists "Users can read own question notes" on public.user_question_notes;
create policy "Users can read own question notes"
  on public.user_question_notes
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own question notes" on public.user_question_notes;
create policy "Users can insert own question notes"
  on public.user_question_notes
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own question notes" on public.user_question_notes;
create policy "Users can update own question notes"
  on public.user_question_notes
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own question notes" on public.user_question_notes;
create policy "Users can delete own question notes"
  on public.user_question_notes
  for delete
  to authenticated
  using (auth.uid() = user_id);
