create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question_text text not null check (char_length(trim(question_text)) >= 5),
  category text not null check (char_length(trim(category)) >= 2),
  points integer not null default 1 check (points >= 1),
  image_url text,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.answers (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  answer_text text not null,
  media_url text,
  is_correct boolean not null default false,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.test_results (
  id bigint generated by default as identity primary key,
  user_name text not null default 'Student',
  user_id uuid references auth.users(id) on delete set null,
  score integer not null default 0 check (score >= 0),
  total_points integer not null default 0 check (total_points >= 0),
  total_questions integer not null default 0 check (total_questions >= 0),
  correct_questions integer not null default 0 check (correct_questions >= 0),
  duration_seconds integer not null default 0 check (duration_seconds >= 0),
  answers jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists answers_question_id_idx
  on public.answers (question_id);

create index if not exists questions_created_at_idx
  on public.questions (created_at desc);

create index if not exists test_results_created_at_idx
  on public.test_results (created_at desc);

grant select on public.questions, public.answers to anon, authenticated;
grant insert on public.test_results to anon, authenticated;
grant select on public.test_results to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

alter table public.test_results enable row level security;

drop policy if exists "Anyone can create test results" on public.test_results;
create policy "Anyone can create test results"
  on public.test_results
  for insert
  to anon, authenticated
  with check (user_id is null or auth.uid() = user_id);

drop policy if exists "Users can read own test results" on public.test_results;
create policy "Users can read own test results"
  on public.test_results
  for select
  to authenticated
  using (auth.uid() = user_id);
